# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/shssoichiro/oxipng
    rev: v9.0.0
    hooks:
    -   id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]
