var subtitles = [
"interweb shenanigans",
"scroll for sexi bod",
"coolest website of the millennium",
"what's the deal with this website?",
"$$$ big big bucks bucks $$$",
"up for golf?",
"up for frolf?",
"cut to: int. my room - forever",
"gif or gif?",
"windows 95 not supported",
"get me a cold and fizzy cocaine-cola",
"noding is for cerds",
"*funny caption*",
"sometimes i think you don't care",
"humble beginnings as a scratch user",
"oh golly it's jason bourne",
"holly carp!",
"no xss here (so don't try)",
"now you're playing with power",
"not on sega",
"allan, please add details!",
"holaoy caprarp!",
"follow me on super mario maker 2: X6G-XB3-4XF",
"hoyl parc!",
"not on 32x adapters",
"arms sweating, palms sweating, mom's sweating",
"give me a drink, bartender",
"my name's not shayne, kid",
"corn you believe colonel?",
"404 subtitle ain't been found",
"may its gland endure 1000 years!",
"betwixt two ferns",
"open thy eyes, see light",
"youtube star, and liar",
"usa! usa! usa! usa! usa! usa! usa! usa!",
"HYPER CHASE PECK II RETURNS",
"SUPER NEW CHASE PECK BROS. U DELUXE GOTY EDITION",
"we want mother 3! am i doing it right?",
"yep yep yep, you're gonna make the sponduli! the moolah!",
"millions of years of code!",
"[stand by]  operate  idle",
"im nto havingeg a stoke,,, u are!!!",
"ƒ∑¢ºµ¬å´3¢",
"hoo!!! hee!!!",
"ubiquitous omnipresence",
"to err is human, but to air is fan",
"when thou are stupidious, i laughest at thy",
"don't forget to commit and push",
"the sign painter",
"i just loveeee my leeetlle infernooo",
"why is your cousin such a wet sandwich?",
"i love you, but you don't know what you're talking about",
"did you tell them that those were the lord's chips?",
"crying and screaming and farting",
"i'm mr. greenz",
"chase peck for president",
"gimme da gorbage",
"space badger 64",
"in the theatre centre, you can put buttre on your popcorne",
"so i booked a ticket to japan",
"$999.99 for no ads! (cheap!)",
"_ <",
"CONGRATULATION. THIS STORY IS HAPPY END.",
"benadryl cumberbash",
"it works*!",
"it has been said.",
"wickerpedia",
"it's a rough-n-tumble world, y'know?",
"ya think it's gonna go dis way, it go dat way",
"i'm james phillips",
"tron jon",
"i chwahna chween",
"i'm a no-nonsense man. down to the nitty-gritty.",
"i'm a no-nonsense man. i use x86 assembly.",
"purchase a chest of chase-coins >> $99.99! <<"
];